package soexample.umeng.com.zhoukao1.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import soexample.umeng.com.zhoukao1.model.PubusBean;

import soexample.umeng.com.zhoukao1.greendao.PubusBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pubusBeanDaoConfig;

    private final PubusBeanDao pubusBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pubusBeanDaoConfig = daoConfigMap.get(PubusBeanDao.class).clone();
        pubusBeanDaoConfig.initIdentityScope(type);

        pubusBeanDao = new PubusBeanDao(pubusBeanDaoConfig, this);

        registerDao(PubusBean.class, pubusBeanDao);
    }
    
    public void clear() {
        pubusBeanDaoConfig.clearIdentityScope();
    }

    public PubusBeanDao getPubusBeanDao() {
        return pubusBeanDao;
    }

}
